services:
  mycontainer:
    build: .
    image: "docker.io/longdevdatabase/oracle_rofl:latest@sha256:efacccf6359972592510165a905e778b8979f722b537a249d11bb71d8183929b"     # Always provide FQDN image names!
    platform: linux/amd64
    volumes:
      - my-volume:/root/.my-volume              # Persistent per-machine storage.
      - /run/rofl-appd.sock:/run/rofl-appd.sock # appd REST API.
    environment:
      - CONTRACT_ADDRESS=1aF1c6e7bfA26b7977e1388324304fdcF675eE76            # See `oasis rofl secret` command.
      - TICKER=ROSEUSDT

volumes:
  my-volume:
